[project]
name = "sensai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "transformers>=4.53.2",
    "torch>=2.7.1",
    "pytest>=8.4.1",
]
